version: '3'
services:
 db:
 image: mysql
 environment:
 MYSQL_ROOT_PASSWORD: root
 volumes:
 - db_data:/var/lib/mysql
 networks:
 - my-network
 phpmyadmin:
 image: phpmyadmin/phpmyadmin
 ports:
 - "8080:80"
 networks:
 - my-network
volumes:
 db_data:
networks:
 my-network:
